// Generated by CoffeeScript 1.8.0
(function() {
  var worker, _;

  _ = require('lodash');

  worker = function(items) {
    return _.where(items, {
      'active': true
    });
  };

  module.exports = worker;

}).call(this);
