// Generated by CoffeeScript 1.8.0
(function() {
  var worker, _;

  _ = require('lodash');

  worker = function(items) {
    var average, overperform, result, total, underperform;
    result = [];
    items = _.sortBy(items, 'income');
    total = _.reduce(items, function(sum, freelancer) {
      return sum + freelancer.income;
    }, 0);
    average = total / _.size(items);
    underperform = _.filter(items, function(freelancer) {
      return freelancer.income <= average;
    });
    overperform = _.filter(items, function(freelancer) {
      return freelancer.income > average;
    });
    return {
      "average": average,
      "underperform": underperform,
      "overperform": overperform
    };
  };

  module.exports = worker;

}).call(this);
